
quarkus.application.name=ms_product
quarkus.http.port=8086

# Database
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=bodgen
quarkus.datasource.password=bodgen123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/bodgendb

# Desactivar base de datos temporal de Quarkus (Dev Services)
quarkus.datasource.devservices.enabled=false

# Configuración de Hibernate ORM
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# Opcional: Para ver los valores de los parámetros en el log de SQL
quarkus.hibernate-orm.log.bind-parameters=true

#OBSERVABILIDAD
quarkus.otel.enabled=true

quarkus.otel.exporter.otlp.traces.endpoint=http://localhost:4317
quarkus.otel.exporter.otlp.traces.protocol=grpc

quarkus.otel.exporter.otlp.metrics.endpoint=http://localhost:4317
quarkus.otel.exporter.otlp.metrics.protocol=grpc

quarkus.otel.traces.sampler=always_on

quarkus.otel.resource.attributes=service.name=ms-product,service.version=1.0.0,deployment.environment=development

quarkus.otel.instrument.rest=true

quarkus.micrometer.enabled=true
quarkus.micrometer.registry-enabled-default=true
quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.export.prometheus.path=/metrics

# Formato para la consola
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p traceId=%X{traceId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{3.3}] (%t) %s%e%n

# Si también usas logs en archivo, aplica el mismo formato
quarkus.log.file.enable=true
quarkus.log.file.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p traceId=%X{traceId}, spanId=%X{spanId} [%c{3.3}] (%t) %s%e%n

# Kafka
kafka.bootstrap.servers=localhost:9092

mp.messaging.incoming.orders.connector=smallrye-kafka
mp.messaging.incoming.orders.topic=orders
#mp.messaging.incoming.orders.value.deserializer=io.quarkus.kafka.client.serialization.ObjectMapperDeserializer
#mp.messaging.incoming.orders.value.deserializer=org.mpravia.message.consumer.dto.OrderCreatedEvent
#mp.messaging.incoming.orders.value.deserializer.type=org.mpravia.message.consumer.dto.OrderCreatedEvent